name: Deploy Nginx

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          sudo usermod -aG docker $USER
          newgrp docker

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      # - name: install the gcloud cli
      #   uses: google-github-actions/setup-gcloud@v0.5.0
      #   with:
      #     project_id: wordpress-test-project-429717
      #     service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      #     export_default_credentials:

      # - name: build and push the docker image
      #   env:
      #     GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      #   run: |
      #     gcloud auth configure-docker us-central1-docker.pkg.dev
      #     docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/wordpress-portfolio/nginx:latest .
      #     docker tag wordpress-portfolio gcr-io/$GOOGLE_PROJECT/wordpress-portfolio/nginx:latest
      #     docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/wordpress-portfolio/nginx:latest

      # - name: push in vm instance
      #   env:
      #     GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      #   run: |
      #     gcloud computer ssh $VM_INSTANCE --zone $ZONE --command "
      #     gcloud auth configure-docker; docker pull gcr."

      - name: Authenticate Docker to Google Cloud
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t gcr.io/wordpress-test-project-429717/gcp-wordpress-demo .

      - name: Push Docker image to Google Container Registry
        run: docker push gcr.io/wordpress-test-project-429717/gcp-wordpress-demo

      - name: SSH into Google VM, pull Docker image, and download file
        run: |
          gcloud compute ssh test-wordpress-portfolio --zone us-central1-c --command "
            gcloud auth configure-docker;
            docker pull gcr.io/wordpress-test-project-429717/gcp-wordpress-demo;
          "
